projects:
  usersapp:
    schemaPath: amplify/backend/api/usersapp/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: scr/API_TEST.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: null
        maxDepth: 2
